from conv_class import *

POSITIVE_CATEGORY = conv_stations('**repeat**',None,None,None,'positive_thinking_category.py',False)
positive_next_next_next = conv_stations('''Are you respected in your office? Is your work recognized by your superiors?''',  POSITIVE_CATEGORY  ,  POSITIVE_CATEGORY  ,None,None,False) 
positive_next_next = conv_stations('''Are you facing any sort of work related stress in your life?''',  POSITIVE_CATEGORY  ,positive_next_next_next,None,None,False)
positive_nextt = conv_stations('''Are you facing any sort of work related stress in your life?''',positive_next_next_next,  POSITIVE_CATEGORY  ,None,None,False)
positive_next = conv_stations('''Do you believe that your work environment is apt for you?''',positive_nextt,positive_next_next,None,None,False)
positive = conv_stations('''Do you find contentment and satisfaction in your job?''',  POSITIVE_CATEGORY  ,positive_next,None,None,False)
ASSERTIVENESS_CATEGORY =  conv_stations('**repeat**',None,None,None,'assertiveness_category.py',False)
assertiveness_next_next_next = conv_stations('''Do you feel that you are as qualified for your job as your colleagues?''',positive,  ASSERTIVENESS_CATEGORY  ,None,None,False) 
assertiveness_next_next = conv_stations('''Do you feel that by disagreeing with your boss on day to day issues, you are not being polite?''',  ASSERTIVENESS_CATEGORY  ,assertiveness_next_next_next,None,None,False)
assertiveness_nextt = conv_stations('''Do you feel that by disagreeing with your boss on day to day issues, you are not being polite?''',assertiveness_next_next_next,positive,None,None,False)
assertiveness_next = conv_stations('''Do you feel that by firmly asserting your opinions during office meetings, you are showing aggression?''',assertiveness_next_next,assertiveness_nextt,None,None,False)
assertiveness = conv_stations('''Do you think you can afford to make some petty work mistakes on a regular basis?''',positive,assertiveness_next,None,None,False)
HEALTH_CATEGORY = conv_stations('**repeat**',None,None,None,'health_category.py',False)
health_next_next_next = conv_stations('''Do you exercise daily?''',assertiveness,  HEALTH_CATEGORY  ,None,None,False) 
health_next_next = conv_stations('''In terms of what you eat, how much you exercise daily, do you think you have developed a healthy lifestyle?''',health_next_next_next,  HEALTH_CATEGORY  ,None,None,False)
health_nextt = conv_stations('''In terms of what you eat, how much you exercise daily, do you think you have developed a healthy lifestyle?''',assertiveness,health_next_next_next,None,None,False)
health_next = conv_stations('''Do you sleep for more than 7 hours daily?''',health_nextt,health_next_next,None,None,False) 
health = conv_stations('''Are you suffering from some chronic or acute health disorder? It includes anything from restlessness to diabetes''',health_next,assertiveness,None,None,False)
TIME_CATEGORY = conv_stations('**repeat**',None,None,None,'time_management_category.py',False)
time_next_next_next = conv_stations('''Do you have some hobbies or activities which you regularly engage in during your free time?''',health,  TIME_CATEGORY  ,None,None,False)
time_next_next = conv_stations('''Are you able to give ample time to your family? ''',time_next_next_next,  TIME_CATEGORY  ,None,None,False)
time_nextt = conv_stations('''Are you able to give ample time to your family? ''',health,time_next_next_next,None,None,False)
time_next = conv_stations('''Do you always wake up at a fixed time in the morning?''',time_nextt,time_next_next,None,None,False)
time = conv_stations('''Do you sleep for more than 7 hours daily?''',health,time_next,None,None,False)

time.start_conv()